### ISSUE TITLE
Steel Dist recipie costs zero

### ISSUE THREAD

**Issue by thorsummoner** [judos/hardCrafting#28]
fixed by #27

**Comment by GodricSeer** [comment]
I am not sure if simply setting a minimum of 1 is the correct solution to this.  Steel from iron plates costs 5 plates, which is somewhere between 4 and 5 crushed iron.  The automatic calculations is supposed to make the recipe about 20% more efficient than making steel from plates, so it should cost 3-4 crushed iron, but this fix would make it only cost 1.  While this fixes the 0 cost recipe, there is still a more fundamental problem in the calculation of the steel recipes.

**Comment by judos** [comment]
Well for now i go with the "minimum 1", if the recipes are changed with a different mod it is hard to stay consistent and balanced. Maybe if you give some more hints to the other mods which change these recipes we can find a better approach.

**Comment by judos** [comment]
oh, I just saw now that there is a general problem with the calculation of iron-plates needed to smelt steel-plates. Therefore yes before it was actually not working at all. And of course the minimum of 1 item is far too few. It's intended to be 4 items instead of the usual 5.
The calculation will be fixed with v0.5.5, but also the minimum of 1 i leave if any other mods change the recipe...

**Comment by thorsummoner** [comment]
it would probably be good to clamp any values to expected ranges. i don't
know if this is done anywhere else in the mod- hope the maintainer is aware
